#!/usr/bin/env bash

URL="http://192.168.20.110/status"
DIR=$(dirname "$0")
DB_PATH="$DIR/data.sqlite"

for i in {0..5}; do
    (   curl -s "$URL" | $DIR/transform-sqlite | \
        xargs -I % sqlite3 -line $DB_PATH \
        "INSERT INTO stats VALUES(%);"
    )&
    sleep 10
done

